spring:
  profiles:
    active: local
  datasource:
    continue-on-error: true
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:tcp://localhost:9093/mem:management_db_9093
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:

logging:
  level:
    root: info
    jdbc:
      sqlonly: info
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off
